[chapter]
= Representation METS header element (element metsHdr)
There are no specific requirements for the header element in a CITS 3D HM Representation METS. The 3D HM Representation metsHdr element should comply with the metsHdr requirements in the appropriate Information Package profile and can be used to identify specific agents related to a Heritage Model representation.

== Representation METS descriptive metadata section (element dmdSec)
There are no specific requirements in CITS 3D HM for the Representation METS descriptive metadata section.

== Representation METS administrative metadata section (element amdSec)
The administrative metadata section contains four sub-sections each used to record different types of metadata for package content: - technical metadata (element techMD) records technical metadata,; - rights metadata (element rightsMD) records intellectual property rights information; - source metadata (element sourceMD) records descriptive technical or rights metadata for an analogue source for a digital object; and – digital provenance metadata (element digiprovMD) records digital preservation information, e.g. audit information for an object’s lifecycle.

The CSIP (and METS) categorise preservation metadata as administrative metadata, specifically digital provenance metadata (following the avaiable Guidelines published by the PREMIS EC Guidelines: http://www.loc.gov/standards/premis/Guidelines2017-premismets.pdf) and hence all preservation metadata should be referenced from single or multiple digiprovMD elements within the amdSec.

Note that CSPM requires that all PREMIS is referenced from the digiprovMD element, including PREMIS Rights information and not via a separate rightsMD statement. 

There are no specific requirements in CITS 3D HM for the representation METS administrative metadata section.

== Representation METS file metadata section (element fileSec)
The CSIP does not make use of the METS fileSec element mandatory, but it is strongly recommended. In CITS 3D HM the use of the METS fileSec element at the Representation  level becomes mandatory, such as to reference the file groups containing data, Paradata Documentation, Authentication Documentation and Other Documentation.
