===== Root METS administrative metadata section (element amdSec)
The administrative metadata section contains four sub-sections each used to record different types of metadata for package content: technical metadata (element techMD) records technical metadata, rights metadata (element rightsMD) records intellectual property rights information, source metadata (element sourceMD) records descriptive technical or rights metadata for an analogue source for a digital object, and digital provenance metadata (element digiprovMD) records digital preservation information, e.g. audit information for an object’s lifecycle.

The CSIP (and METS) categorise preservation metadata as administrative metadata, specifically digital provenance metadata (following the available Guidelines published in the  Guidelines for using PREMIS with METS for exchange: http://www.loc.gov/standards/premis/Guidelines2017-premismets.pdf) and hence all PREMIS  metada should be referenced from a single or multiple digiprovMD elements within the amdSec. 

Note that CSPM requires that all PREMIS is referenced from the digiprovMD element, including PREMIS Rights information and not via a separate rightsMD statement. 

